In [2]:
import pandas as pd
import numpy as np
import sklearn

URL = 'https://raw.githubusercontent.com/bobby6007/PortfolioProjects/main/cleaned_tashkent_housing'
df=pd.read_csv(URL)

from sklearn.model_selection import train_test_split
train_set, test_set =train_test_split(df, test_size=0.2, random_state=35)

X_train=train_set.drop('price',axis=1)
y = train_set['price'].copy()

X_num = housing.drop(['district', 'location'],axis=1)

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

num_pipeline = Pipeline([
          ('std_scaler', StandardScaler())             
])

In [4]:
from sklearn.compose import ColumnTransformer

num_attribs = list(X_num)
cat_attribs = ['district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', OrdinalEncoder(), cat_attribs)
])

In [5]:
X_prepared = full_pipeline.fit_transform(X_train)

In [6]:
X_prepared[0:5,:]

array([[ 0.38495289, -0.11138749,  1.0273817 ,  1.14499213,  5.        ],
       [-0.57143469, -1.03250677,  0.1376173 ,  1.14499213,  2.        ],
       [ 0.38495289, -0.20667569,  0.1376173 , -0.76927335,  5.        ],
       [ 0.38495289,  0.52386718,  0.5824995 , -0.38642025,  1.        ],
       [-0.57143469, -0.55606576,  0.1376173 , -0.76927335, 11.        ]])

Machine learning

In [7]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

In [8]:
LR_model.fit(X_prepared, y)

LinearRegression()

Evaluating the model

In [13]:
# selecting random 5 rows
test_data = X_train.sample(5)
test_data

location           district  \
6314       город Ташкент, Мирабадский район, Ул Кунаева        Мирабадский   
2782  город Ташкент, Мирзо-Улугбекский район, Карасу...  Мирзо-Улугбекский   
3984   город Ташкент, Мирзо-Улугбекский район, Феруза-2  Мирзо-Улугбекский   
5156  город Ташкент, Чиланзарский район, Катта козир...       Чиланзарский   
5688  город Ташкент, Мирзо-Улугбекский район, жилой ...  Мирзо-Улугбекский   

      rooms  size  level  max_levels  
6314      4    90      4           4  
2782      3    80      5           5  
3984      1    42      1           4  
5156      3    70      8           9  
5688      2    66      2           8

In [14]:
# yuqoridagi qatorlarga mos keluvchi narxlarni ajratib olamiz (biz aynan shu qiymatlarni bashorat qilishimiz kerak)
test_label = y.loc[test_data.index]
test_label

6314    90000
2782    39000
3984    26500
5156    49500
5688    55000
Name: price, dtype: int64

In [15]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[ 1.34134046,  0.58739265,  0.1376173 , -0.76927335,  1.        ],
       [ 0.38495289,  0.26976531,  0.5824995 , -0.38642025,  2.        ],
       [-1.52782227, -0.93721857, -1.19702931, -0.76927335,  2.        ],
       [ 0.38495289, -0.04786202,  1.91714611,  1.14499213,  6.        ],
       [-0.57143469, -0.17491296, -0.75214711,  0.76213904,  2.        ]])

In [16]:
predicted_data = LR_model.predict(test_data_prepared)
predicted_data

array([67793.7207984 , 63062.71173601, 40687.43829263, 45392.65308437,
       61618.22019061])

In [17]:
pd.DataFrame({'Prognoz':predicted_data, 'Real baxosi': test_label})

Prognoz  Real baxosi
6314  67793.720798        90000
2782  63062.711736        39000
3984  40687.438293        26500
5156  45392.653084        49500
5688  61618.220191        55000

In [19]:
X_test = test_set.drop('price', axis=1)
X_test

location           district  \
648   город Ташкент, Шайхантахурский район, 1-й прое...    Шайхантахурский   
4084  город Ташкент, Яккасарайский район, Малая коль...      Яккасарайский   
7091  город Ташкент, Мирзо-Улугбекский район, Корзин...  Мирзо-Улугбекский   
134   город Ташкент, Юнусабадский район, Юнусабад 11...       Юнусабадский   
2793  город Ташкент, Чиланзарский район, Чиланзар 10...       Чиланзарский   
...                                                 ...                ...   
449           город Ташкент, Чиланзарский район, Мукими       Чиланзарский   
2130  город Ташкент, Мирзо-Улугбекский район, Карасу...  Мирзо-Улугбекский   
3792  город Ташкент, Мирзо-Улугбекский район, Улица ...  Мирзо-Улугбекский   
6043  город Ташкент, Учтепинский район, Чиланзар 24-...        Учтепинский   
3356  город Ташкент, Юнусабадский район, Юнусабад 7-...       Юнусабадский   

      rooms  size  level  max_levels  
648       1    41      4           6  
4084      3    70      2           5  
7091      3    82      8           9  
134       2    61      1           4  
2793      3   111      5           6  
...     ...   ...    ...         ...  
449       3   110      2           8  
2130      2    65      5           5  
3792      1    22      4           4  
6043      2    48      5           5  
3356      3   105      5           6  

[1476 rows x 6 columns]

In [20]:
y_test = test_set['price'].copy()
y_test

648      23542
4084     70000
7091     58000
134      55000
2793     85000
         ...  
449     160000
2130     37000
3792     19000
6043     27000
3356     66455
Name: price, Length: 1476, dtype: int64

In [21]:
X_test_prepared = full_pipeline.transform(X_test)

In [22]:
y_predicted = LR_model.predict(X_test_prepared)

In [23]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

24370.106130171604


Training with other models

Decision Tree

In [24]:
from sklearn.tree import DecisionTreeRegressor
Tree_model = DecisionTreeRegressor()
Tree_model.fit(X_prepared, y)

DecisionTreeRegressor()

In [25]:
y_predicted = Tree_model.predict(X_test_prepared)

In [26]:
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

21839.89318692488


Random Forest

In [27]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(X_prepared, y)

RandomForestRegressor()

In [28]:
y_predicted = RF_model.predict(X_test_prepared)
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

19143.350018722984


Cross Validation 

In [29]:
X = df.drop("price", axis=1)
y = df["price"].copy()

X_prepared = full_pipeline.transform(X)

In [30]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Std.dev:", scores.std())

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
scores = cross_val_score(LR_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)

In [33]:
display_scores(LR_rmse_scores)

Scores: [20752.35867762 18846.67454747 24366.88449853 26988.9516788
 27071.55215691 26293.15561581 22907.21948782 24949.23773576
 21142.1262093  17022.24101739]
Mean: 23034.040162540146
Std.dev: 3323.9490001633244


Decision tree

In [34]:
scores = cross_val_score(Tree_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [21541.60674282 24380.63423136 28455.67063982 27000.16383131
 31055.39543678 25263.11808265 26831.77306153 22560.5595376
 25308.34536035 17354.52015574]
Mean: 24975.178707997235
Std.dev: 3645.161149858546


Random Forest

In [35]:
scores = cross_val_score(RF_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [16725.55962627 17115.09923685 22842.34639625 23250.26835044
 22062.71181463 21320.83685064 20674.55570082 19207.07298678
 18409.70314991 13705.19035678]
Mean: 19531.334446938963
Std.dev: 2910.809796741566
